# Generated by Django 2.0.4 on 2018-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historyname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=12, null=True)),
                ('usedname', models.CharField(blank=True, max_length=60, null=True)),
                ('lastaccess', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historyname',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=12, null=True)),
                ('iconaddr', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'icon',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastaccess', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('isgirl', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True)),
                ('icid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main',
            },
        ),
        migrations.CreateModel(
            name='Noblelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=12, null=True)),
                ('nl', models.CharField(blank=True, max_length=1, null=True)),
                ('accesstime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noblelist',
            },
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
