# Generated by Django 2.0.4 on 2018-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180531_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='isgirl',
            field=models.IntegerField(blank=True, choices=[(b'\x00', 'Male'), (b'\x01', 'Female')], null=True),
        ),
    ]
