# Generated by Django 2.0.4 on 2018-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180531_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='isgirl',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
