# Generated by Django 2.0.4 on 2018-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180531_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='icid',
        ),
        migrations.AddField(
            model_name='icon',
            name='lastaccess',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='isgirl',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='noblelist',
            name='nl',
            field=models.CharField(blank=True, choices=[('0', '未知'), ('1', '骑士'), ('2', '子爵'), ('3', '伯爵'), ('4', '公爵'), ('5', '国王'), ('6', '皇帝'), ('7', '游侠'), ('-', '普通')], max_length=1, null=True),
        ),
    ]
