# Generated by Django 2.0.4 on 2018-06-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20180603_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdlv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'band',
            },
        ),
        migrations.CreateModel(
            name='Bandname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField(blank=True, null=True)),
                ('bandname', models.CharField(blank=True, max_length=10, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bandname',
            },
        ),
        migrations.AddField(
            model_name='band',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Bandname'),
        ),
        migrations.AddField(
            model_name='band',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Main'),
        ),
    ]
