# Generated by Django 2.0.4 on 2018-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='oid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='roomid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rstr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
