# Generated by Django 2.0.4 on 2018-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20180608_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('logo', models.CharField(blank=True, max_length=4, null=True)),
                ('ownerid', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Clubmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'clubmember',
            },
        ),
        migrations.AlterField(
            model_name='band',
            name='bid',
            field=models.IntegerField(choices=[(1, '17丷'), (2, '401')]),
        ),
    ]
