# Generated by Django 2.0.4 on 2018-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20180609_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('giftname', models.CharField(blank=True, max_length=30, null=True)),
                ('gifttype', models.SmallIntegerField(blank=True, choices=[(1, 'fishball'), (2, 'sharkfin')], null=True)),
                ('contrib', models.IntegerField(blank=True, null=True)),
                ('mimg', models.CharField(blank=True, max_length=150, null=True)),
                ('himg', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
                ('intro', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
        migrations.CreateModel(
            name='Giftrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('gid', models.IntegerField()),
                ('sendtime', models.IntegerField()),
                ('roomid', models.IntegerField()),
                ('maxhits', models.IntegerField()),
            ],
            options={
                'db_table': 'giftrecord',
            },
        ),
        migrations.AlterField(
            model_name='band',
            name='bid',
            field=models.IntegerField(choices=[(1, '17丷'), (2, '401'), (3, '猪芳芳'), (4, '马蚤'), (5, '驴酱灬'), (6, '雙馬尾'), (7, '安神'), (8, '小僵尸'), (9, '大帅熊'), (10, '憨厚哒'), (11, '大官'), (12, 'YJJ'), (13, '张大仙'), (14, '女流'), (15, '196'), (16, '辣椒儿'), (17, 'Np虚'), (18, '小痒虫'), (19, '小人参'), (20, 'Sao狐'), (21, '蘑菇'), (22, '寅子'), (23, '雪美眉'), (24, '二珂'), (25, '樱圆圆'), (26, '菠咕咕'), (27, '全针'), (28, '突突突'), (29, '呆妹儿'), (30, '嘉年华'), (31, '飞儿'), (32, '小便当'), (33, '猫腻'), (34, '鱼乐'), (35, '集团军'), (36, '小豆包'), (37, '一发'), (38, 'lol'), (39, '嗨宝'), (40, '大司马'), (46, 'XDD')]),
        ),
    ]
