# Generated by Django 2.0.4 on 2018-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20180612_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cicon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
