# Generated by Django 2.0.4 on 2018-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20180612_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='hititv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
