# Generated by Django 2.0.4 on 2018-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20180625_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('refid', models.IntegerField()),
                ('pubtime', models.DateTimeField()),
                ('thumb', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, max_length=140)),
                ('btext', models.BinaryField(blank=True, max_length=560)),
                ('istext', models.BooleanField(default=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('delid', models.IntegerField(blank=True, null=True)),
                ('deltime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
